---@meta
-- Generated by AiluHeadTool. Individual Script API declarations are split by module.

---@class Vec2
---@field x number
---@field y number
---@type fun(): Vec2
---@overload fun(x: number, y: number): Vec2
Vec2 = nil

---@class Vec3
---@field x number
---@field y number
---@field z number
---@type fun(): Vec3
---@overload fun(x: number, y: number, z: number): Vec3
Vec3 = nil

---@class Quaternion
---@field x number
---@field y number
---@field z number
---@field w number
---@type fun(): Quaternion
---@overload fun(x: number, y: number, z: number, w: number): Quaternion
Quaternion = nil

require("scriptengine")
require("scriptentity")
require("scriptcamera")
require("scriptscene")
require("scriptinput")
require("scripttime")
require("scriptphysics2d")

---@class AiluScript
---@field entity ScriptEntity
---@field scene ScriptScene
local AiluScript = {}

function AiluScript:OnCreate() end

function AiluScript:OnEnable() end

function AiluScript:OnDisable() end

---@param dt number
function AiluScript:OnFixedUpdate(dt) end

---@param dt number
function AiluScript:OnUpdate(dt) end

---@param dt number
---@param render_alpha number
function AiluScript:OnLateUpdate(dt, render_alpha) end

function AiluScript:OnDestroy() end

---@type ScriptEngine
engine = nil

---@type ScriptInput
input = nil

---@type ScriptTime
time = nil
---@type ScriptPhysics2D
physics2d = nil
