---@meta
-- Generated by AiluHeadTool. Individual Script API declarations are split by module.

---@class Vec2
---@field x number
---@field y number
---@overload fun(): Vec2
---@overload fun(x: number, y: number): Vec2
Vec2 = nil

---@class Vec3
---@field x number
---@field y number
---@field z number
---@overload fun(): Vec3
---@overload fun(x: number, y: number, z: number): Vec3
Vec3 = nil

---@class Quaternion
---@field x number
---@field y number
---@field z number
---@field w number
---@overload fun(): Quaternion
---@overload fun(x: number, y: number, z: number, w: number): Quaternion
Quaternion = nil

---@class Color
---@field r number
---@field g number
---@field b number
---@field a number
---@overload fun(): Color
---@overload fun(r: number, g: number, b: number, a: number): Color
Color = nil

require("scriptengine")
require("scriptassetvalue")
require("scriptentity")
require("scriptcamera")
require("scriptscene")
require("scriptinput")
require("scripttime")
require("scriptphysics2d")
require("scriptrigidbody2d")
require("scriptspriterenderer")
require("scriptanimator")
require("scriptaudiosource")
require("scriptaudio")

---@class AiluScript
---@field entity ScriptEntity
---@field scene ScriptScene
local AiluScript = {}

function AiluScript:on_create() end

function AiluScript:on_enable() end

---@param dt number
function AiluScript:on_fixed_update(dt) end

---@param dt number
function AiluScript:on_update(dt) end

---@param dt number
---@param render_alpha number
function AiluScript:on_late_update(dt, render_alpha) end

function AiluScript:on_disable() end

function AiluScript:on_destroy() end

function AiluScript:on_reload() end
