---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class Vec2
---@field x number
---@field y number
---@type fun(): Vec2
---@overload fun(x: number, y: number): Vec2
Vec2 = nil

---@class Vec3
---@field x number
---@field y number
---@field z number
---@type fun(): Vec3
---@overload fun(x: number, y: number, z: number): Vec3
Vec3 = nil

---@class Quaternion
---@field x number
---@field y number
---@field z number
---@field w number
---@type fun(): Quaternion
---@overload fun(x: number, y: number, z: number, w: number): Quaternion
Quaternion = nil

---@class ScriptEngine
local ScriptEngine = {}

---@param message string
function ScriptEngine.log(message) end

---@return number
function ScriptEngine.time() end

---@return number
function ScriptEngine.delta_time() end

---@return number
function ScriptEngine.fixed_delta_time() end

---@return number
function ScriptEngine.render_alpha() end

---@class ScriptTransform
local ScriptTransform = {}

---@return boolean
function ScriptTransform:is_valid() end

---@return Vec3
function ScriptTransform:get_local_position() end

---@param position Vec3
function ScriptTransform:set_local_position(position) end

---@return Quaternion
function ScriptTransform:get_local_rotation() end

---@param rotation Quaternion
function ScriptTransform:set_local_rotation(rotation) end

---@return Vec3
function ScriptTransform:get_local_scale() end

---@param scale Vec3
function ScriptTransform:set_local_scale(scale) end

---@class ScriptEntity
local ScriptEntity = {}

---@return boolean
function ScriptEntity:is_valid() end

---@return string
function ScriptEntity:get_name() end

---@param name string
function ScriptEntity:set_name(name) end

---@return string
function ScriptEntity:get_guid() end

---@return ScriptTransform
function ScriptEntity:get_transform() end

function ScriptEntity:destroy() end

---@class ScriptPhysics2D
local ScriptPhysics2D = {}

---@param entity ScriptEntity
---@return boolean
function ScriptPhysics2D.is_valid_body(entity) end

---@param entity ScriptEntity
---@param position Vec2
function ScriptPhysics2D.set_position(entity, position) end

---@param entity ScriptEntity
---@return Vec2
function ScriptPhysics2D.get_position(entity) end

---@param entity ScriptEntity
---@param velocity Vec2
function ScriptPhysics2D.set_linear_velocity(entity, velocity) end

---@param entity ScriptEntity
---@return Vec2
function ScriptPhysics2D.get_linear_velocity(entity) end

---@param entity ScriptEntity
---@param velocity number
function ScriptPhysics2D.set_angular_velocity(entity, velocity) end

---@param entity ScriptEntity
---@param force Vec2
function ScriptPhysics2D.add_force(entity, force) end

---@param entity ScriptEntity
---@param impulse Vec2
function ScriptPhysics2D.add_impulse(entity, impulse) end

---@class ScriptScene
local ScriptScene = {}

---@return boolean
function ScriptScene:is_valid() end

---@param guid string
---@return ScriptEntity
function ScriptScene:find_entity(guid) end

---@param name string
---@return ScriptEntity
function ScriptScene:find_entity_by_name(name) end

---@param name string
---@return ScriptEntity
function ScriptScene:create_entity(name) end

---@class ScriptInput
local ScriptInput = {}

---@param action_name string
---@return boolean
function ScriptInput:is_pressed(action_name) end

---@param action_name string
---@return boolean
function ScriptInput:is_down(action_name) end

---@param action_name string
---@return number
function ScriptInput:get_float(action_name) end

---@param action_name string
---@return Vec2
function ScriptInput:get_vector2(action_name) end

---@class ScriptTime
local ScriptTime = {}

---@return number
function ScriptTime:get_delta_time() end

---@return number
function ScriptTime:get_fixed_delta_time() end

---@return number
function ScriptTime:get_render_alpha() end

---@return number
function ScriptTime:get_time() end

---@class AiluScript
---@field entity ScriptEntity
---@field scene ScriptScene
local AiluScript = {}

function AiluScript:OnCreate() end

function AiluScript:OnEnable() end

function AiluScript:OnDisable() end

---@param dt number
function AiluScript:OnFixedUpdate(dt) end

---@param dt number
function AiluScript:OnUpdate(dt) end

---@param dt number
---@param render_alpha number
function AiluScript:OnLateUpdate(dt, render_alpha) end

function AiluScript:OnDestroy() end

---@type ScriptEngine
engine = nil

---@type ScriptInput
input = nil

---@type ScriptTime
time = nil
