---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptRaycastHit2D
---@field distance number
---@field entity ScriptEntity
---@field normal Vec2
---@field point Vec2
---@field valid boolean
ScriptRaycastHit2D = {}

---@return boolean
function ScriptRaycastHit2D:is_valid() end

---@return ScriptEntity
function ScriptRaycastHit2D:get_entity() end

---@return Vec2
function ScriptRaycastHit2D:get_point() end

---@return Vec2
function ScriptRaycastHit2D:get_normal() end

---@return number
function ScriptRaycastHit2D:get_distance() end

---@class ScriptPhysics2D
ScriptPhysics2D = {}

---@type ScriptPhysics2D
physics2d = {}

---@param origin Vec2
---@param direction Vec2
---@param distance number
---@param layer_mask number
---@return ScriptRaycastHit2D|nil
function ScriptPhysics2D.raycast(origin, direction, distance, layer_mask) end

---@param center Vec2
---@param radius number
---@param layer_mask number
---@return ScriptRaycastHit2D[]
function ScriptPhysics2D.overlap_circle(center, radius, layer_mask) end

---@param center Vec2
---@param size Vec2
---@param rotation number
---@param layer_mask number
---@return ScriptRaycastHit2D[]
function ScriptPhysics2D.overlap_box(center, size, rotation, layer_mask) end

