---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptTime
---@field delta_time number
---@field fixed_delta_time number
---@field render_alpha number
---@field time number
ScriptTime = {}

---@type ScriptTime
time = {}

---@return number
function ScriptTime:get_delta_time() end

---@return number
function ScriptTime:get_fixed_delta_time() end

---@return number
function ScriptTime:get_render_alpha() end

---@return number
function ScriptTime:get_time() end

