---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptCollider2D
---@field shape_count number
---@field valid boolean
ScriptCollider2D = {}

---@return boolean
function ScriptCollider2D:is_valid() end

---@return number
function ScriptCollider2D:get_shape_count() end

---@param callback fun(arg0: ScriptEntity, arg1: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_collision_enter(callback) end

---@param callback fun(arg0: ScriptEntity, arg1: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_collision_exit(callback) end

---@param callback fun(arg0: ScriptEntity)
---@return integer subscription_id
function ScriptCollider2D:on_trigger_enter(callback) end

---@param callback fun(arg0: ScriptEntity)
---@return integer subscription_id
function ScriptCollider2D:on_trigger_exit(callback) end

