---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptComponent
ScriptComponent = {}

---@return boolean
function ScriptComponent:is_valid() end

---@return string
function ScriptComponent:get_type_name() end

---@return boolean
function ScriptComponent:is_enabled() end

---@param enabled boolean
function ScriptComponent:set_enabled(enabled) end

---@param property string
---@param value number
---@return boolean
function ScriptComponent:set_float(property, value) end

---@param property string
---@param value number
---@return boolean
function ScriptComponent:set_int(property, value) end

---@param property string
---@param value boolean
---@return boolean
function ScriptComponent:set_bool(property, value) end

---@param property string
---@param value string
---@return boolean
function ScriptComponent:set_string(property, value) end

---@param property string
---@param value Vec2
---@return boolean
function ScriptComponent:set_vector2(property, value) end

---@param property string
---@param value Vec3
---@return boolean
function ScriptComponent:set_vector3(property, value) end

---@param size Vec2
---@param is_trigger boolean
---@return boolean
function ScriptComponent:add_box_shape(size, is_trigger) end

---@param entity ScriptEntity
---@param type_name string
---@return boolean
function ScriptComponent.add(entity, type_name) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value number
---@return boolean
function ScriptComponent.set_entity_float(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value boolean
---@return boolean
function ScriptComponent.set_entity_bool(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value Vec3
---@return boolean
function ScriptComponent.set_entity_vector3(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param size Vec2
---@param is_trigger boolean
---@return boolean
function ScriptComponent.add_entity_box_shape(entity, type_name, size, is_trigger) end

---@class ScriptTransform
---@field forward Vec3
---@field local_position Vec3
---@field local_rotation Quaternion
---@field local_scale Vec3
---@field position Vec3
---@field right Vec3
---@field rotation Quaternion
---@field scale Vec3
---@field up Vec3
---@field valid boolean
ScriptTransform = {}

---@return boolean
function ScriptTransform:is_valid() end

---@return Vec3
function ScriptTransform:get_local_position() end

---@param position Vec3
function ScriptTransform:set_local_position(position) end

---@return Quaternion
function ScriptTransform:get_local_rotation() end

---@param rotation Quaternion
function ScriptTransform:set_local_rotation(rotation) end

---@return Vec3
function ScriptTransform:get_local_scale() end

---@param scale Vec3
function ScriptTransform:set_local_scale(scale) end

---@return Vec3
function ScriptTransform:get_position() end

---@param position Vec3
function ScriptTransform:set_position(position) end

---@return Quaternion
function ScriptTransform:get_rotation() end

---@param rotation Quaternion
function ScriptTransform:set_rotation(rotation) end

---@return Vec3
function ScriptTransform:get_scale() end

---@param scale Vec3
function ScriptTransform:set_scale(scale) end

---@return Vec3
function ScriptTransform:get_forward() end

---@return Vec3
function ScriptTransform:get_right() end

---@return Vec3
function ScriptTransform:get_up() end

---@class ScriptEntity
---@field animator ScriptAnimator|nil
---@field audio ScriptAudioSource|nil
---@field collider2d ScriptCollider2D|nil
---@field guid string
---@field name string
---@field rigid_body2d ScriptRigidBody2D|nil
---@field sprite ScriptSpriteRenderer|nil
---@field transform ScriptTransform
ScriptEntity = {}

---@return boolean
function ScriptEntity:is_valid() end

---@return string
function ScriptEntity:get_name() end

---@param name string
function ScriptEntity:set_name(name) end

---@return string
function ScriptEntity:get_guid() end

---@return ScriptTransform
function ScriptEntity:get_transform() end

---@return ScriptRigidBody2D|nil
function ScriptEntity:get_rigid_body2d() end

---@return ScriptCollider2D|nil
function ScriptEntity:get_collider2d() end

---@return ScriptSpriteRenderer|nil
function ScriptEntity:get_sprite() end

---@return ScriptAnimator|nil
function ScriptEntity:get_animator() end

---@return ScriptAudioSource|nil
function ScriptEntity:get_audio() end

function ScriptEntity:destroy() end

---@param type_name string
---@return boolean
function ScriptEntity:has_component(type_name) end

---@param type_name string
---@return boolean
function ScriptEntity:remove_component(type_name) end

