---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptSpriteRenderer
---@field color Color
---@field flip_x boolean
---@field flip_y boolean
---@field order number
---@field sprite ScriptAssetValue
---@field valid boolean
---@field visible boolean
ScriptSpriteRenderer = {}

---@return boolean
function ScriptSpriteRenderer:is_valid() end

---@return ScriptAssetValue
function ScriptSpriteRenderer:get_sprite() end

---@param sprite ScriptAssetValue
function ScriptSpriteRenderer:set_sprite(sprite) end

---@return boolean
function ScriptSpriteRenderer:is_visible() end

---@param visible boolean
function ScriptSpriteRenderer:set_visible(visible) end

---@return boolean
function ScriptSpriteRenderer:is_flip_x() end

---@param flip_x boolean
function ScriptSpriteRenderer:set_flip_x(flip_x) end

---@return boolean
function ScriptSpriteRenderer:is_flip_y() end

---@param flip_y boolean
function ScriptSpriteRenderer:set_flip_y(flip_y) end

---@return number
function ScriptSpriteRenderer:get_order() end

---@param order number
function ScriptSpriteRenderer:set_order(order) end

---@return Color
function ScriptSpriteRenderer:get_color() end

---@param color Color
function ScriptSpriteRenderer:set_color(color) end

