---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptEngine
ScriptEngine = {}

---@param message string
function ScriptEngine.log_info(message) end

---@param message string
function ScriptEngine.log_warning(message) end

---@param message string
function ScriptEngine.log_error(message) end

