---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptComponent
ScriptComponent = {}

---@return boolean
function ScriptComponent:is_valid() end

---@return string
function ScriptComponent:get_type_name() end

---@return boolean
function ScriptComponent:is_enabled() end

---@param enabled boolean
function ScriptComponent:set_enabled(enabled) end

---@param property string
---@param value number
---@return boolean
function ScriptComponent:set_float(property, value) end

---@param property string
---@param value number
---@return boolean
function ScriptComponent:set_int(property, value) end

---@param property string
---@param value boolean
---@return boolean
function ScriptComponent:set_bool(property, value) end

---@param property string
---@param value string
---@return boolean
function ScriptComponent:set_string(property, value) end

---@param property string
---@param value Vec2
---@return boolean
function ScriptComponent:set_vector2(property, value) end

---@param property string
---@param value Vec3
---@return boolean
function ScriptComponent:set_vector3(property, value) end

---@param size Vec2
---@param is_trigger boolean
---@return boolean
function ScriptComponent:add_box_shape(size, is_trigger) end

---@param sprite_guid string
---@return boolean
function ScriptComponent:set_sprite(sprite_guid) end

---@param entity ScriptEntity
---@param type_name string
---@return boolean
function ScriptComponent.add(entity, type_name) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value number
---@return boolean
function ScriptComponent.set_entity_float(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value boolean
---@return boolean
function ScriptComponent.set_entity_bool(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param property string
---@param value Vec3
---@return boolean
function ScriptComponent.set_entity_vector3(entity, type_name, property, value) end

---@param entity ScriptEntity
---@param type_name string
---@param size Vec2
---@param is_trigger boolean
---@return boolean
function ScriptComponent.add_entity_box_shape(entity, type_name, size, is_trigger) end

---@param entity ScriptEntity
---@param type_name string
---@param sprite_guid string
---@return boolean
function ScriptComponent.set_entity_sprite(entity, type_name, sprite_guid) end

---@class ScriptTransform
ScriptTransform = {}

---@return boolean
function ScriptTransform:is_valid() end

---@return Vec3
function ScriptTransform:get_local_position() end

---@param position Vec3
function ScriptTransform:set_local_position(position) end

---@return Quaternion
function ScriptTransform:get_local_rotation() end

---@param rotation Quaternion
function ScriptTransform:set_local_rotation(rotation) end

---@return Vec3
function ScriptTransform:get_local_scale() end

---@param scale Vec3
function ScriptTransform:set_local_scale(scale) end

---@class ScriptEntity
ScriptEntity = {}

---@return boolean
function ScriptEntity:is_valid() end

---@return string
function ScriptEntity:get_name() end

---@param name string
function ScriptEntity:set_name(name) end

---@return string
function ScriptEntity:get_guid() end

---@return ScriptTransform
function ScriptEntity:get_transform() end

function ScriptEntity:destroy() end

---@param type_name string
---@return boolean
function ScriptEntity:has_component(type_name) end

---@param type_name string
---@return boolean
function ScriptEntity:remove_component(type_name) end

---@class ScriptAssetValue
ScriptAssetValue = {}

---@return ScriptAssetValue
function ScriptAssetValue.sprite() end

---@return ScriptAssetValue
function Sprite() end

---@return ScriptAssetValue
function ScriptAssetValue.texture2d() end

---@return ScriptAssetValue
function Texture2D() end

---@return ScriptAssetValue
function ScriptAssetValue.material() end

---@return ScriptAssetValue
function Material() end

---@return ScriptAssetValue
function ScriptAssetValue.mesh() end

---@return ScriptAssetValue
function Mesh() end

---@return ScriptAssetValue
function ScriptAssetValue.skeleton_mesh() end

---@return ScriptAssetValue
function SkeletonMesh() end

---@return ScriptAssetValue
function ScriptAssetValue.animation_clip() end

---@return ScriptAssetValue
function AnimationClip() end

---@return ScriptAssetValue
function ScriptAssetValue.audio_clip() end

---@return ScriptAssetValue
function AudioClip() end

---@return ScriptAssetValue
function ScriptAssetValue.script() end

---@return ScriptAssetValue
function Script() end

---@return boolean
function ScriptAssetValue:is_valid() end

---@return string
function ScriptAssetValue:get_guid() end

---@return string
function ScriptAssetValue:get_name() end

---@return string
function ScriptAssetValue:get_path() end

---@return string
function ScriptAssetValue:get_asset_type() end

