---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptRigidBody2D
---@field angular_velocity number
---@field fixed_rotation boolean
---@field gravity_scale number
---@field valid boolean
---@field velocity Vec2
ScriptRigidBody2D = {}

---@return boolean
function ScriptRigidBody2D:is_valid() end

---@return Vec2
function ScriptRigidBody2D:get_velocity() end

---@param velocity Vec2
function ScriptRigidBody2D:set_velocity(velocity) end

---@return number
function ScriptRigidBody2D:get_angular_velocity() end

---@param velocity number
function ScriptRigidBody2D:set_angular_velocity(velocity) end

---@return number
function ScriptRigidBody2D:get_gravity_scale() end

---@param scale number
function ScriptRigidBody2D:set_gravity_scale(scale) end

---@return boolean
function ScriptRigidBody2D:is_fixed_rotation() end

---@param fixed boolean
function ScriptRigidBody2D:set_fixed_rotation(fixed) end

---@param force Vec2
function ScriptRigidBody2D:add_force(force) end

---@param impulse Vec2
function ScriptRigidBody2D:add_impulse(impulse) end

---@param torque number
function ScriptRigidBody2D:add_torque(torque) end

