---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptCamera
ScriptCamera = {}

---@return boolean
function ScriptCamera:is_valid() end

---@return Vec3
function ScriptCamera:get_position() end

---@param position Vec3
function ScriptCamera:set_position(position) end

---@return Quaternion
function ScriptCamera:get_rotation() end

---@param rotation Quaternion
function ScriptCamera:set_rotation(rotation) end

---@return Vec3
function ScriptCamera:get_forward() end

---@return number
function ScriptCamera:get_fov() end

---@param fov number
function ScriptCamera:set_fov(fov) end

---@return number
function ScriptCamera:get_near_clip() end

---@param near_clip number
function ScriptCamera:set_near_clip(near_clip) end

---@return number
function ScriptCamera:get_far_clip() end

---@param far_clip number
function ScriptCamera:set_far_clip(far_clip) end

---@return number
function ScriptCamera:get_aspect() end

---@param aspect number
function ScriptCamera:set_aspect(aspect) end

---@return boolean
function ScriptCamera:is_orthographic() end

---@param enabled boolean
function ScriptCamera:set_orthographic(enabled) end

---@return number
function ScriptCamera:get_orthographic_size() end

---@param size number
function ScriptCamera:set_orthographic_size(size) end

---@param direction Vec3
---@param up Vec3
function ScriptCamera:look_to(direction, up) end

---@param world_position Vec3
---@return Vec2
function ScriptCamera:world_to_screen(world_position) end

---@param screen_position Vec2
---@param depth number
---@return Vec3
function ScriptCamera:screen_to_world(screen_position, depth) end

