---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptAudioSource
---@field loop boolean
---@field pitch number
---@field valid boolean
---@field volume number
ScriptAudioSource = {}

---@return boolean
function ScriptAudioSource:is_valid() end

function ScriptAudioSource:play() end

function ScriptAudioSource:stop() end

---@return number
function ScriptAudioSource:get_volume() end

---@param volume number
function ScriptAudioSource:set_volume(volume) end

---@return number
function ScriptAudioSource:get_pitch() end

---@param pitch number
function ScriptAudioSource:set_pitch(pitch) end

---@return boolean
function ScriptAudioSource:is_loop() end

---@param loop boolean
function ScriptAudioSource:set_loop(loop) end

