---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptTime
ScriptTime = {}

---@return number
function ScriptTime:get_delta_time() end

---@return number
function ScriptTime:get_fixed_delta_time() end

---@return number
function ScriptTime:get_render_alpha() end

---@return number
function ScriptTime:get_time() end

