---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptAudio
ScriptAudio = {}

---@type ScriptAudio
audio = {}

---@param clip ScriptAssetValue
---@param position Vec3
---@return boolean
function ScriptAudio.play_one_shot(clip, position) end

function ScriptAudio.stop_music() end

