---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptScene
---@field main_camera ScriptCamera
ScriptScene = {}

---@return ScriptScene
function ScriptScene.current_scene() end

---@return boolean
function ScriptScene:is_valid() end

---@param guid string
---@return ScriptEntity
function ScriptScene:find_entity(guid) end

---@param name string
---@return ScriptEntity
function ScriptScene:find_entity_by_name(name) end

---@param name string
---@return ScriptEntity
function ScriptScene:find(name) end

---@param guid string
---@return ScriptEntity
function ScriptScene:find_guid(guid) end

---@overload fun(self: ScriptScene, prefab: ScriptAssetValue): ScriptEntity
---@param name string
---@return ScriptEntity
function ScriptScene:create_entity(name) end

---@param prefab ScriptAssetValue
---@return ScriptEntity
function ScriptScene:spawn(prefab) end

---@return ScriptCamera
function ScriptScene:get_main_camera() end

