---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptAssetValue
---@field valid boolean
ScriptAssetValue = {}

---@return ScriptAssetValue
function ScriptAssetValue.sprite() end

---@return ScriptAssetValue
function Sprite() end

---@return ScriptAssetValue
function ScriptAssetValue.texture2d() end

---@return ScriptAssetValue
function Texture2D() end

---@return ScriptAssetValue
function ScriptAssetValue.material() end

---@return ScriptAssetValue
function Material() end

---@return ScriptAssetValue
function ScriptAssetValue.mesh() end

---@return ScriptAssetValue
function Mesh() end

---@return ScriptAssetValue
function ScriptAssetValue.skeleton_mesh() end

---@return ScriptAssetValue
function SkeletonMesh() end

---@return ScriptAssetValue
function ScriptAssetValue.animation_clip() end

---@return ScriptAssetValue
function AnimationClip() end

---@return ScriptAssetValue
function ScriptAssetValue.audio_clip() end

---@return ScriptAssetValue
function AudioClip() end

---@return ScriptAssetValue
function ScriptAssetValue.script() end

---@return ScriptAssetValue
function Script() end

---@return ScriptAssetValue
function ScriptAssetValue.prefab() end

---@return ScriptAssetValue
function Prefab() end

---@return boolean
function ScriptAssetValue:is_valid() end

