---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptContact2D
---@field normal Vec2
---@field other_object_type number
---@field other_shape number
---@field point Vec2
---@field self_shape number
ScriptContact2D = {}

---@return Vec2
function ScriptContact2D:get_point() end

---@return Vec2
function ScriptContact2D:get_normal() end

---@return number
function ScriptContact2D:get_self_shape() end

---@return number
function ScriptContact2D:get_other_shape() end

---@return number
function ScriptContact2D:get_other_object_type() end

