---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@enum CollisionChannel2D
CollisionChannel2D = {
    WorldStatic = 0,
    WorldDynamic = 1,
    Player = 2,
    Enemy = 3,
    Projectile = 4,
    Trigger = 5,
    Pickup = 6,
    Count = 7,
}

---@class ScriptCollider2D
---@field shape_count number
---@field valid boolean
ScriptCollider2D = {}

---@return boolean
function ScriptCollider2D:is_valid() end

---@return number
function ScriptCollider2D:get_shape_count() end

---@param target_channel CollisionChannel2D
---@param callback fun(other: ScriptEntity, contact: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_collision_enter(target_channel, callback) end

---@param target_channel CollisionChannel2D
---@param callback fun(other: ScriptEntity, contact: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_collision_exit(target_channel, callback) end

---@param target_channel CollisionChannel2D
---@param callback fun(other: ScriptEntity, contact: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_trigger_enter(target_channel, callback) end

---@param target_channel CollisionChannel2D
---@param callback fun(other: ScriptEntity, contact: ScriptContact2D)
---@return integer subscription_id
function ScriptCollider2D:on_trigger_exit(target_channel, callback) end

