---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptAnimator
---@field speed number
---@field valid boolean
ScriptAnimator = {}

---@return boolean
function ScriptAnimator:is_valid() end

---@param name string
---@return boolean
function ScriptAnimator:play(name) end

---@return number
function ScriptAnimator:get_speed() end

---@param speed number
function ScriptAnimator:set_speed(speed) end

