---@meta
-- Generated by AiluHeadTool from Script reflection metadata. Do not edit.

---@class ScriptScene
ScriptScene = {}

---@return boolean
function ScriptScene:is_valid() end

---@param guid string
---@return ScriptEntity
function ScriptScene:find_entity(guid) end

---@param name string
---@return ScriptEntity
function ScriptScene:find_entity_by_name(name) end

---@param name string
---@return ScriptEntity
function ScriptScene:create_entity(name) end

---@return ScriptCamera
function ScriptScene:get_main_camera() end

